models.py
from django.db import models

# Create your models here.

forms.py
from django import forms
from django.core.validators import RegexValidator, FileExtensionValidator

#create forms here
YES_NO_CHOICES = (
    (0, 'No'),
    (1, 'Yes')
)
class SqlServerLogInForm(forms.Form):
    ip_address = forms.GenericIPAddressField()
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.widgets.PasswordInput()
    )

class CreateSqlTableForm(forms.Form):
    table_name = forms.CharField(
        validators=[RegexValidator(regex="^[a-zA-Z_][a-zA-Z0-9_\s]+$", message='Invalid table name. Table name must start with upper or lowwer letter (a-z) or underscore. Table name can contain only upper or lower letters (a-z), digits (0-9), underscores or spaces.')]
    )
    excel_file = forms.FileField(
        widget = forms.widgets.FileInput(),
        validators=[FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]
    )

class UpdateSqlTableForm(forms.Form):
    table_name_u = forms.CharField(
        validators=[RegexValidator(regex="^[a-zA-Z_][a-zA-Z0-9_\s]+$", message='Invalid table name. Table name must start with upper or lowwer letter (a-z) or underscore. Table name can contain only upper or lower letters (a-z), digits (0-9), underscores or spaces.')]
    )
    excel_file_u = forms.FileField(
        widget = forms.widgets.FileInput(),
        validators=[FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]
    )
    drop_table = forms.ChoiceField(
        choices=YES_NO_CHOICES,
        widget=forms.widgets.Select()
    )

    def __init__(self, *args, **kwargs):
        table_list = kwargs.pop('table_list', None)
        super().__init__(*args, *kwargs)
        self.fields['table_name_u'].widget = forms.widgets.Select(choices=tuple([(table, table) for table in table_list]))

    

views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods
from excelToSqlApp import forms
from datetime import datetime
from excelToSqlApp import services
import json

# Create your views here.
@require_http_methods(['GET', 'POST'])
def sqlServerLogin(request):
    if request.method == 'POST':
        form = forms.SqlServerLogInForm(request.POST)
        if form.is_valid():
            success = services.sqlLogin(request.POST['ip_address'], request.POST['username'], request.POST['password'])
            if success.get('hasErrors') == False:
                #return HttpResponse(content=success.get('databases'))
                request.session['ip_address'] = request.POST['ip_address']
                request.session['username'] = request.POST['username']
                request.session['password'] = request.POST['password']
                request.session.set_expiry = 0
                databases = success.get('databases')
                return render(
                    request,
                    'excelToSqlApp/sql_server_content.html',
                    {
                        'databases': databases,
                        'sql_server_address': request.session['ip_address'],
                        'sql_server_user': request.session['username']
                    }
                )
                '''json_data = json.dumps(success)
                return JsonResponse(data = json_data, safe=False)'''
            else:
                return HttpResponse(content=success.get('errors'))
    else:
        form = forms.SqlServerLogInForm()
    return render(
        request,
        'excelToSqlApp/sql_server_login.html',
        {
            'form': form
        }
    )

@require_http_methods(['GET'])
def connectToSqlDb(request, db_name):
    success = services.connectToSqlDb(request.session['ip_address'], request.session['username'], request.session['password'], db_name)
    if success.get('hasErrors') == False:
        request.session['db_name'] = db_name
        tables = success.get('databases')
        return render(
            request,
            'excelToSqlApp/sql_server_db_tables.html',
            {
                'tables': tables,
                'database_name': db_name,
                'sql_server_address': request.session['ip_address'],
                'sql_server_user': request.session['username']
            }
        )
    else:
        return HttpResponse(content=success.get('errors'))

@require_http_methods(['GET', 'POST'])
def createSqlTable(request):
    if request.method == 'POST':
        form = forms.CreateSqlTableForm(request.POST, request.FILES)
        if form.is_valid():
            response = services.CreateTableFromExcel(request.session['ip_address'], request.session['username'], request.session['password'], request.session['db_name'], request.POST['table_name'], request.FILES['excel_file'])
            return JsonResponse(data=response)
    else:
        form = forms.CreateSqlTableForm()
    return render(
        request,
        'excelToSqlApp/_sql_server_create_table.html',
        {
            'form': form
        }
    )

@require_http_methods(['GET', 'POST'])
def updateSqlTable(request):
    data = services.connectToSqlDb(request.session['ip_address'], request.session['username'], request.session['password'], request.session['db_name'])
    if request.method == 'POST':
        form = forms.UpdateSqlTableForm(request.POST, request.FILES, table_list=data.get('databases'))
        if form.is_valid():
            response = services.updateSqltableFromExcel(request.session['ip_address'], request.session['username'], request.session['password'], request.session['db_name'], request.POST['table_name_u'], request.FILES['excel_file_u'], bool(int(request.POST['drop_table'])))
            return JsonResponse(data=response)
    else:
        form = forms.UpdateSqlTableForm(table_list=data.get('databases'))
    return render(
        request,
        'excelToSqlApp/_sql_server_update_table.html',
        {
            'form': form
        }
    )

templates/excelToSqlApp/_sql_server_create_table.html
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
        <form id="frm_create_table" method="POST" enctype="multipart/form-data" action="{% url 'createsqltable' %}">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-green">{{ form.table_name.label}}</span>
                </div>
                {{ form.table_name }}
            </div>
            {% if form.table_name.errors %}
            {% for error in form.table_name.errors %}
            <p class="text-danger">{{error|escape}}</p>
            {% endfor %}
            {% endif %}

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-green">{{ form.excel_file.label}}</span>
                </div>
                <div class="custom-file">
                    {{ form.excel_file }}
                    <label id="lblFile" class="custom-file-label" for="id_excel_file">Choose excel file</label>
                </div>

            </div>
            {% if form.excel_file.errors %}
            {% for error in form.excel_file.errors %}
            <p class="text-danger">{{error|escape}}</p>
            {% endfor %}
            {% endif %}
            <div class="float-right">
                <input class="btn btn-success bg-green" value="Create table" type="submit" />
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    $(function () {
        $('#id_table_name').addClass('form-control');
        $("#id_excel_file").on("change", function () {
            var files = $(this).prop('files');
            var names = $.map(files, function (val) { return val.name; });
            if (names.toString().length > 50) {
                $("#lblFile").text(names.toString().substring(0, 50) + "...");
            }
            else {
                $("#lblFile").text(names.toString());
            }

        });
    });

</script>

templates/excelToSqlApp/_sql_server_update_table.html
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
        <form id="frm_update_table" method="POST" enctype="multipart/form-data" action="{% url 'updatesqltable' %}">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-white">Table name</span>
                </div>
                {{ form.table_name_u }}
            </div>
            {% if form.table_name_u.errors %}
            {% for error in form.table_name_u.errors %}
            <p class="text-danger">{{error|escape}}</p>
            {% endfor %}
            {% endif %}

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-white">Excel file</span>
                </div>
                <div class="custom-file">
                    {{ form.excel_file_u }}
                    <label id="lblFileU" class="custom-file-label" for="id_excel_file_u">Choose excel file</label>
                </div>

            </div>
            {% if form.excel_file_u.errors %}
            {% for error in form.excel_file_u.errors %}
            <p class="text-danger">{{error|escape}}</p>
            {% endfor %}
            {% endif %}

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-white">{{ form.drop_table.label}}</span>
                </div>
                {{ form.drop_table }}
            </div>
            {% if form.drop_table.errors %}
            {% for error in form.drop_table.errors %}
            <p class="text-danger">{{error|escape}}</p>
            {% endfor %}
            {% endif %}

            <div class="float-right">
                <input class="btn btn-primary" value="Update table" type="submit" />
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    $(function () {
        $('#id_table_name_u').addClass('form-control');
        $('#id_drop_table').addClass('form-control');
        $("#id_excel_file_u").on("change", function () {
            var files = $(this).prop('files');
            var names = $.map(files, function (val) { return val.name; });
            if (names.toString().length > 50) {
                $("#lblFileU").text(names.toString().substring(0, 50) + "...");
            }
            else {
                $("#lblFileU").text(names.toString());
            }

        });
    });

</script>

templates/excelToSqlApp/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <script src="{% static 'excelToSqlApp/js/jquery-3.0.0.min.js' %}"></script>
    
    <link rel="stylesheet" type="text/css" href="{% static 'excelToSqlApp/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'excelToSqlApp/css/site.css' %}" />

</head>

<body>
    <nav class="navbar navbar-dark bg-green fixed-top">
        <div class="container-fluid">
            <div class="navbar-item navbar-brand font-weight-bold">
                <span>Excel to SQL</span>
            </div>
            {% if sql_server_address and sql_server_user %}
            <div class="float-right ml-auto">
                Sql server: {{sql_server_address}}  User: {{sql_server_user}}
            </div>
            <div class="clearfix"></div>
            {% endif %}
        </div>
    </nav>


    <div class="container-fluid body-content">
        {% block content %}{% endblock %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal_alert">
        <div class="modal-dialog">
            <div id="modal_alert_content" class="modal-content">
                <div class="modal-header">
                    <h5 id="modal_alert_text" class="modal-title">Alert</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'excelToSqlApp/js/popper.min.js' %}"></script>
    <script src="{% static 'excelToSqlApp/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'excelToSqlApp/js/respond.min.js' %}"></script>
</body>

</html>

templates/excelToSqlApp/sql_server_content.html
{% extends "excelToSqlApp/layout.html" %}
{% block title %}
Sql server explorer
{% endblock %}
{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-12">
        <div class="card-columns">
    {% for db in databases %}
    <div class="card">
        <div class="card-body">
            <div class="media">
                <a class="d-flex" href="{% url 'connecttosqldb' db %}">
                    <img src="{% static 'excelToSqlApp/images/icons8-database-64.png' %}" alt="db" class="align-self-center mr-3">
                </a>
                <div class="media-body">
                    <br />
                    <a class="database-link" href="{% url 'connecttosqldb' db %}">
                        <h5>{{db}}</h5>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}  
</div>
    </div>
</div>

{% endblock %}

templates/excelToSqlApp/sql_server_create_table.html
{% extends "excelToSqlApp/layout.html" %}
{% block title %}
Create table
{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input class="btn btn-dark" value="Create table" type="submit" />
</form>
{% endblock %}

templates/excelToSqlApp/sql_server_db_tables.html
{% extends "excelToSqlApp/layout.html" %}
{% block title %}
Database explorer
{% endblock %}
{% block content %}
{% load static %}
{% load render_partial %}
<div class="row">
    <div class="col-md-4">
        <span class="text-xl">
            <img src="{% static 'excelToSqlApp/images/icons8-database-64.png' %}" alt="db" class="mr-1">
            {{database_name}}
        </span>
        <p class="mt-3 border border-success border-top-0 border-left-0 border-right-0">
            <a class="tables-link text-xl" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
                Tables
            </a>
        </p>
        <div class="collapse show" id="tables">
            <ul>
                {% for t in tables %}
                <li>{{t}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-md-8">

        <div id="accordion">

            <div class="card">
                <div class="card-header p-0">
                    <a class="btn btn-success bg-green btn-lg btn-block m-0" data-toggle="collapse" href="#collapseOne">
                        Create new table from excel
                    </a>
                </div>
                <div id="collapseOne" class="collapse" data-parent="#accordion">
                    <div id="panel_create_table" class="card-body">
                        {% render_partial 'createsqltable' %}
                    </div>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header p-0">
                    <a class="collapsed btn btn-primary btn-lg btn-block m-0" data-toggle="collapse" href="#collapseTwo">
                        Update existing table from excel
                    </a>
                </div>
                <div id="collapseTwo" class="collapse" data-parent="#accordion">
                    <div id="panel_update_table" class="card-body">
                        {% render_partial 'updatesqltable' %}
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>
<script src="{% static 'excelToSqlApp/js/custom/sql_server_db_tables.js' %}"></script>
{% endblock %}

templates/excelToSqlApp/sql_server_login.html
{% extends "excelToSqlApp/layout.html" %}
{% block title %}
Sql Login
{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h3 class="text-green">Connect to SQL Server</h3>
            <form method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-green">{{ form.ip_address.label}}</span>
                    </div>
                    {{ form.ip_address }}
                </div>
                {% if form.ip_address.errors %}
                {% for error in form.ip_address.errors %}
                <p class="text-danger">{{ error|escape }}</p>
                {% endfor %}
                {% endif %}

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-green">{{ form.username.label}}</span>
                    </div>
                    {{ form.username }}
                </div>
                {% if form.username.errors %}
                {% for error in form.username.errors %}
                <p class="text-danger">{{ error|escape }}</p>
                {% endfor %}
                {% endif %}

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-green">{{ form.password.label}}</span>
                    </div>
                    {{ form.password }}
                </div>
                {% if form.password.errors %}
                {% for error in form.password.errors %}
                <p class="text-danger">{{ error|escape }}</p>
                {% endfor %}
                {% endif %}

                <input class="btn btn-success btn-block bg-green" value="Connect" type="submit" />
            </form>
            {% load static %}
            <script src="{% static 'excelToSqlApp/js/custom/sql_server_login.js' %}"></script>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

templates/excelToSqlApp/sql_server_update_table.html
{% extends "excelToSqlApp/layout.html" %}
{% block title %}
Update table
{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <input class="btn btn-dark" value="Update" type="submit" />
</form>
{% endblock %}